WhiteKing:   file 'graphics\wking.dat'
WhiteQueen:  file 'graphics\wqueen.dat'
WhiteKnight: file 'graphics\wknight.dat'
WhiteRook:   file 'graphics\wrook.dat'
WhiteBishop: file 'graphics\wbishop.dat'
WhitePawn:   file 'graphics\wpawn.dat'

BlackKing:   file 'graphics\bking.dat'
BlackQueen:  file 'graphics\bqueen.dat'
BlackKnight: file 'graphics\bknight.dat'
BlackRook:   file 'graphics\brook.dat'
BlackBishop: file 'graphics\bbishop.dat'
BlackPawn:   file 'graphics\bpawn.dat'

LightSquare: ;file 'graphics\ltsquare.dat'
DarkSquare:  ;file 'graphics\dksquare.dat'

